apiVersion: v1
kind: Service
metadata:
  labels:
    postgresql: postgresql
  name: postgresql
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    postgresql: postgresql
