apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ksqldb-server
  name: ksqldb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ksqldb-server
    spec:
      containers:
        - env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: broker:9092
            - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
              value: "true"
            - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
              value: "true"
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:28088
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8081"
          image: confluentinc/ksqldb-server:0.23.1
          name: ksqldb-server
          ports:
            - containerPort: 28088
              protocol: TCP
      hostname: ksqldb-server
      restartPolicy: Always
